# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometry.proto',
  package='mission_protobuf',
  serialized_pb=_b('\n\x0egeometry.proto\x12\x10mission_protobuf\"\xa0\x02\n\x08Geometry\x12-\n\x04pose\x18\x01 \x02(\x0b\x32\x1f.mission_protobuf.Geometry.Pose\x1a\xe4\x01\n\x04Pose\x12\x37\n\x08position\x18\x01 \x02(\x0b\x32%.mission_protobuf.Geometry.Pose.Point\x12?\n\x0borientation\x18\x02 \x02(\x0b\x32*.mission_protobuf.Geometry.Pose.Quaternion\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x1a\x38\n\nQuaternion\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x12\t\n\x01w\x18\x04 \x02(\x01\x42\x31\n\x1forg.mission_planner.common_msgsB\x0eGeometryProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GEOMETRY_POSE_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='mission_protobuf.Geometry.Pose.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mission_protobuf.Geometry.Pose.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='mission_protobuf.Geometry.Pose.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='mission_protobuf.Geometry.Pose.Point.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=267,
)

_GEOMETRY_POSE_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='mission_protobuf.Geometry.Pose.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mission_protobuf.Geometry.Pose.Quaternion.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='mission_protobuf.Geometry.Pose.Quaternion.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='mission_protobuf.Geometry.Pose.Quaternion.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='mission_protobuf.Geometry.Pose.Quaternion.w', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=325,
)

_GEOMETRY_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='mission_protobuf.Geometry.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='mission_protobuf.Geometry.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='mission_protobuf.Geometry.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GEOMETRY_POSE_POINT, _GEOMETRY_POSE_QUATERNION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=325,
)

_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='mission_protobuf.Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='mission_protobuf.Geometry.pose', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GEOMETRY_POSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=325,
)

_GEOMETRY_POSE_POINT.containing_type = _GEOMETRY_POSE
_GEOMETRY_POSE_QUATERNION.containing_type = _GEOMETRY_POSE
_GEOMETRY_POSE.fields_by_name['position'].message_type = _GEOMETRY_POSE_POINT
_GEOMETRY_POSE.fields_by_name['orientation'].message_type = _GEOMETRY_POSE_QUATERNION
_GEOMETRY_POSE.containing_type = _GEOMETRY
_GEOMETRY.fields_by_name['pose'].message_type = _GEOMETRY_POSE
DESCRIPTOR.message_types_by_name['Geometry'] = _GEOMETRY

Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), dict(

  Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(

    Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
      DESCRIPTOR = _GEOMETRY_POSE_POINT,
      __module__ = 'geometry_pb2'
      # @@protoc_insertion_point(class_scope:mission_protobuf.Geometry.Pose.Point)
      ))
    ,

    Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
      DESCRIPTOR = _GEOMETRY_POSE_QUATERNION,
      __module__ = 'geometry_pb2'
      # @@protoc_insertion_point(class_scope:mission_protobuf.Geometry.Pose.Quaternion)
      ))
    ,
    DESCRIPTOR = _GEOMETRY_POSE,
    __module__ = 'geometry_pb2'
    # @@protoc_insertion_point(class_scope:mission_protobuf.Geometry.Pose)
    ))
  ,
  DESCRIPTOR = _GEOMETRY,
  __module__ = 'geometry_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.Geometry)
  ))
_sym_db.RegisterMessage(Geometry)
_sym_db.RegisterMessage(Geometry.Pose)
_sym_db.RegisterMessage(Geometry.Pose.Point)
_sym_db.RegisterMessage(Geometry.Pose.Quaternion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.mission_planner.common_msgsB\016GeometryProtos'))
# @@protoc_insertion_point(module_scope)
