# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_area.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_area.proto',
  package='mission_protobuf',
  serialized_pb=_b('\n\x12service_area.proto\x12\x10mission_protobuf\"w\n\x0bServiceArea\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\x01\x12\r\n\x05width\x18\x03 \x02(\x01\x12\x0e\n\x06height\x18\x04 \x02(\x01\x12\x10\n\x08\x64iameter\x18\x05 \x02(\x01\x12\x12\n\ntilt_angle\x18\x06 \x02(\x01\x42\x34\n\x1forg.mission_planner.common_msgsB\x11ServiceAreaProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERVICEAREA = _descriptor.Descriptor(
  name='ServiceArea',
  full_name='mission_protobuf.ServiceArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='mission_protobuf.ServiceArea.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='mission_protobuf.ServiceArea.length', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='mission_protobuf.ServiceArea.width', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='mission_protobuf.ServiceArea.height', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diameter', full_name='mission_protobuf.ServiceArea.diameter', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tilt_angle', full_name='mission_protobuf.ServiceArea.tilt_angle', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['ServiceArea'] = _SERVICEAREA

ServiceArea = _reflection.GeneratedProtocolMessageType('ServiceArea', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEAREA,
  __module__ = 'service_area_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.ServiceArea)
  ))
_sym_db.RegisterMessage(ServiceArea)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.mission_planner.common_msgsB\021ServiceAreaProtos'))
# @@protoc_insertion_point(module_scope)
