# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_specification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import task_action_pb2
import time_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_specification.proto',
  package='mission_protobuf',
  serialized_pb=_b('\n\x18task_specification.proto\x12\x10mission_protobuf\x1a\x11task_action.proto\x1a\ntime.proto\"\xef\x01\n\x0eNavigationTask\x12\x36\n\x08location\x18\x01 \x02(\x0b\x32$.mission_protobuf.LocationIdentifier\x12\x41\n\x0borientation\x18\x02 \x02(\x0e\x32,.mission_protobuf.NavigationTask.Orientation\x12)\n\twait_time\x18\x03 \x02(\x0b\x32\x16.mission_protobuf.Time\"7\n\x0bOrientation\x12\t\n\x05NORTH\x10\x01\x12\x08\n\x04\x45\x41ST\x10\x02\x12\t\n\x05SOUTH\x10\x03\x12\x08\n\x04WEST\x10\x04\"\xc1\x02\n\x12TransportationTask\x12\x32\n\x06object\x18\x01 \x02(\x0b\x32\".mission_protobuf.ObjectIdentifier\x12\x35\n\tcontainer\x18\x02 \x01(\x0b\x32\".mission_protobuf.ObjectIdentifier\x12\x1a\n\x12quantity_delivered\x18\x03 \x02(\x04\x12\x1a\n\x12quantity_requested\x18\x04 \x01(\x04\x12\x39\n\x0b\x64\x65stination\x18\x05 \x01(\x0b\x32$.mission_protobuf.LocationIdentifier\x12\x34\n\x06source\x18\x06 \x01(\x0b\x32$.mission_protobuf.LocationIdentifier\x12\x17\n\x0fprocessing_team\x18\x07 \x01(\t\"\x87\x03\n\x04Task\x12\n\n\x02id\x18\x01 \x02(\x04\x12-\n\x04type\x18\x02 \x02(\x0e\x32\x1f.mission_protobuf.Task.TaskType\x12-\n\x06status\x18\x03 \x02(\x0e\x32\x1d.mission_protobuf.Task.Status\x12\x41\n\x13transportation_task\x18\x04 \x01(\x0b\x32$.mission_protobuf.TransportationTask\x12\x39\n\x0fnavigation_task\x18\x05 \x01(\x0b\x32 .mission_protobuf.NavigationTask\"Z\n\x06Status\x12\x0b\n\x07OFFERED\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x0f\n\x0bIN_PROGRESS\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\x0b\n\x07\x41\x42ORTED\x10\x05\x12\x0c\n\x08\x46INISHED\x10\x06\";\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0eTRANSPORTATION\x10\x01\x12\x0e\n\nNAVIGATION\x10\x02\x42-\n\x1forg.mission_planner.common_msgsB\nTaskProtos')
  ,
  dependencies=[task_action_pb2.DESCRIPTOR,time_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_NAVIGATIONTASK_ORIENTATION = _descriptor.EnumDescriptor(
  name='Orientation',
  full_name='mission_protobuf.NavigationTask.Orientation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORTH', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EAST', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOUTH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEST', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=262,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_NAVIGATIONTASK_ORIENTATION)

_TASK_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='mission_protobuf.Task.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFERED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_PROGRESS', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=884,
  serialized_end=974,
)
_sym_db.RegisterEnumDescriptor(_TASK_STATUS)

_TASK_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='mission_protobuf.Task.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPORTATION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAVIGATION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=976,
  serialized_end=1035,
)
_sym_db.RegisterEnumDescriptor(_TASK_TASKTYPE)


_NAVIGATIONTASK = _descriptor.Descriptor(
  name='NavigationTask',
  full_name='mission_protobuf.NavigationTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='mission_protobuf.NavigationTask.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='mission_protobuf.NavigationTask.orientation', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wait_time', full_name='mission_protobuf.NavigationTask.wait_time', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NAVIGATIONTASK_ORIENTATION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=317,
)


_TRANSPORTATIONTASK = _descriptor.Descriptor(
  name='TransportationTask',
  full_name='mission_protobuf.TransportationTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object', full_name='mission_protobuf.TransportationTask.object', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container', full_name='mission_protobuf.TransportationTask.container', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity_delivered', full_name='mission_protobuf.TransportationTask.quantity_delivered', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity_requested', full_name='mission_protobuf.TransportationTask.quantity_requested', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination', full_name='mission_protobuf.TransportationTask.destination', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mission_protobuf.TransportationTask.source', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processing_team', full_name='mission_protobuf.TransportationTask.processing_team', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=641,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='mission_protobuf.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mission_protobuf.Task.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='mission_protobuf.Task.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='mission_protobuf.Task.status', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transportation_task', full_name='mission_protobuf.Task.transportation_task', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='navigation_task', full_name='mission_protobuf.Task.navigation_task', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_STATUS,
    _TASK_TASKTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=1035,
)

_NAVIGATIONTASK.fields_by_name['location'].message_type = task_action_pb2._LOCATIONIDENTIFIER
_NAVIGATIONTASK.fields_by_name['orientation'].enum_type = _NAVIGATIONTASK_ORIENTATION
_NAVIGATIONTASK.fields_by_name['wait_time'].message_type = time_pb2._TIME
_NAVIGATIONTASK_ORIENTATION.containing_type = _NAVIGATIONTASK
_TRANSPORTATIONTASK.fields_by_name['object'].message_type = task_action_pb2._OBJECTIDENTIFIER
_TRANSPORTATIONTASK.fields_by_name['container'].message_type = task_action_pb2._OBJECTIDENTIFIER
_TRANSPORTATIONTASK.fields_by_name['destination'].message_type = task_action_pb2._LOCATIONIDENTIFIER
_TRANSPORTATIONTASK.fields_by_name['source'].message_type = task_action_pb2._LOCATIONIDENTIFIER
_TASK.fields_by_name['type'].enum_type = _TASK_TASKTYPE
_TASK.fields_by_name['status'].enum_type = _TASK_STATUS
_TASK.fields_by_name['transportation_task'].message_type = _TRANSPORTATIONTASK
_TASK.fields_by_name['navigation_task'].message_type = _NAVIGATIONTASK
_TASK_STATUS.containing_type = _TASK
_TASK_TASKTYPE.containing_type = _TASK
DESCRIPTOR.message_types_by_name['NavigationTask'] = _NAVIGATIONTASK
DESCRIPTOR.message_types_by_name['TransportationTask'] = _TRANSPORTATIONTASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK

NavigationTask = _reflection.GeneratedProtocolMessageType('NavigationTask', (_message.Message,), dict(
  DESCRIPTOR = _NAVIGATIONTASK,
  __module__ = 'task_specification_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.NavigationTask)
  ))
_sym_db.RegisterMessage(NavigationTask)

TransportationTask = _reflection.GeneratedProtocolMessageType('TransportationTask', (_message.Message,), dict(
  DESCRIPTOR = _TRANSPORTATIONTASK,
  __module__ = 'task_specification_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.TransportationTask)
  ))
_sym_db.RegisterMessage(TransportationTask)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'task_specification_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.Task)
  ))
_sym_db.RegisterMessage(Task)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.mission_planner.common_msgsB\nTaskProtos'))
# @@protoc_insertion_point(module_scope)
