# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waypoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import task_action_pb2
import geometry_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waypoint.proto',
  package='mission_protobuf',
  serialized_pb=_b('\n\x0ewaypoint.proto\x12\x10mission_protobuf\x1a\x11task_action.proto\x1a\x0egeometry.proto\"\xbc\x02\n\x08Waypoint\x12\x36\n\x08location\x18\x01 \x02(\x0b\x32$.mission_protobuf.LocationIdentifier\x12,\n\x08geometry\x18\x02 \x02(\x0b\x32\x1a.mission_protobuf.Geometry\x12<\n\x0cservice_area\x18\x03 \x01(\x0b\x32&.mission_protobuf.Waypoint.ServiceArea\x12\x13\n\x0bshould_scan\x18\x04 \x01(\x08\x1aw\n\x0bServiceArea\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x0e\n\x06length\x18\x02 \x02(\x01\x12\r\n\x05width\x18\x03 \x02(\x01\x12\x0e\n\x06height\x18\x04 \x02(\x01\x12\x10\n\x08\x64iameter\x18\x05 \x02(\x01\x12\x12\n\ntilt_angle\x18\x06 \x02(\x01\"P\n\x15WaypointConfiguration\x12\n\n\x02id\x18\x01 \x02(\x05\x12+\n\x07wapoint\x18\x02 \x03(\x0b\x32\x1a.mission_protobuf.WaypointB1\n\x1forg.mission_planner.common_msgsB\x0eWaypointProtos')
  ,
  dependencies=[task_action_pb2.DESCRIPTOR,geometry_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WAYPOINT_SERVICEAREA = _descriptor.Descriptor(
  name='ServiceArea',
  full_name='mission_protobuf.Waypoint.ServiceArea',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='mission_protobuf.Waypoint.ServiceArea.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='mission_protobuf.Waypoint.ServiceArea.length', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='mission_protobuf.Waypoint.ServiceArea.width', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='mission_protobuf.Waypoint.ServiceArea.height', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diameter', full_name='mission_protobuf.Waypoint.ServiceArea.diameter', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tilt_angle', full_name='mission_protobuf.Waypoint.ServiceArea.tilt_angle', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=388,
)

_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='mission_protobuf.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='mission_protobuf.Waypoint.location', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='mission_protobuf.Waypoint.geometry', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_area', full_name='mission_protobuf.Waypoint.service_area', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='should_scan', full_name='mission_protobuf.Waypoint.should_scan', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WAYPOINT_SERVICEAREA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=388,
)


_WAYPOINTCONFIGURATION = _descriptor.Descriptor(
  name='WaypointConfiguration',
  full_name='mission_protobuf.WaypointConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mission_protobuf.WaypointConfiguration.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wapoint', full_name='mission_protobuf.WaypointConfiguration.wapoint', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=470,
)

_WAYPOINT_SERVICEAREA.containing_type = _WAYPOINT
_WAYPOINT.fields_by_name['location'].message_type = task_action_pb2._LOCATIONIDENTIFIER
_WAYPOINT.fields_by_name['geometry'].message_type = geometry_pb2._GEOMETRY
_WAYPOINT.fields_by_name['service_area'].message_type = _WAYPOINT_SERVICEAREA
_WAYPOINTCONFIGURATION.fields_by_name['wapoint'].message_type = _WAYPOINT
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['WaypointConfiguration'] = _WAYPOINTCONFIGURATION

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(

  ServiceArea = _reflection.GeneratedProtocolMessageType('ServiceArea', (_message.Message,), dict(
    DESCRIPTOR = _WAYPOINT_SERVICEAREA,
    __module__ = 'waypoint_pb2'
    # @@protoc_insertion_point(class_scope:mission_protobuf.Waypoint.ServiceArea)
    ))
  ,
  DESCRIPTOR = _WAYPOINT,
  __module__ = 'waypoint_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.Waypoint)
  ))
_sym_db.RegisterMessage(Waypoint)
_sym_db.RegisterMessage(Waypoint.ServiceArea)

WaypointConfiguration = _reflection.GeneratedProtocolMessageType('WaypointConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _WAYPOINTCONFIGURATION,
  __module__ = 'waypoint_pb2'
  # @@protoc_insertion_point(class_scope:mission_protobuf.WaypointConfiguration)
  ))
_sym_db.RegisterMessage(WaypointConfiguration)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.mission_planner.common_msgsB\016WaypointProtos'))
# @@protoc_insertion_point(module_scope)
