
WAYPOINT_MARKER     = "/mission_planner_comm/waypoint_marker"
ROBOT_ARM_POSE      = "/joint_states"
MISSION_TASK        = "/mission_planner_comm/mission_task"
MOVE_BASE_FEEDBACK  = "/move_base/feedback"
JOINT_STATE         = "/joint_states"
TODO_TASKS          = "/mission_planner_comm/todo_tasks"
COMPLETED_TASKS     = "/mission_planner_comm/completed_tasks"
CURRENT_TASKS       = "/mission_planner_comm/current_tasks"
HOLDER_LIST         = "/mission_planner_comm/holder_list"
MISSION_STATE       = "/mission_planner_comm/mission_state"